# Generated by Django 4.2.4 on 2023-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakaoId',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
