# Generated by Django 4.2.4 on 2023-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_kakaoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakaoId',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
