# Generated by Django 4.2.4 on 2023-08-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_email_alter_user_kakaoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kakaoId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
