# Generated by Django 4.2.4 on 2023-09-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_usercard_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
