# Generated by Django 4.2.4 on 2023-08-24 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastMessage', models.CharField(max_length=100)),
                ('lastMessageTime', models.DateTimeField(auto_now=True)),
                ('startUser_is_room_deleted', models.BooleanField(default=False)),
                ('endUser_is_room_deleted', models.BooleanField(default=False)),
                ('endUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_room', to=settings.AUTH_USER_MODEL)),
                ('startUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('leftUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='left_user_chat', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_chat', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_chat', to='chatting.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
