branch-defaults:
  deploy:
    environment: Mypath-deploy-env
  main:
    environment: Mypath-deploy-env
  master:
    environment: Mypath-deploy-env
global:
  application_name: Mypath-deploy
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  sc: git
