branch-defaults:
  deploy:
    environment: MyPath-env
  main:
    environment: MyPath-env
  master:
    environment: MyPath-env
global:
  application_name: myPath
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  sc: git
