# Generated by Django 4.2.4 on 2023-09-07 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_path', to='post.path')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_sender', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_step', to='post.step')),
            ],
        ),
    ]
