# Generated by Django 4.2.4 on 2023-09-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='push',
            name='text',
            field=models.CharField(default='none msg', max_length=100),
            preserve_default=False,
        ),
    ]
