# Generated by Django 4.2.4 on 2023-09-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_push_postcommentid_push_stepcommentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='push',
            name='postCommentId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='push',
            name='stepCommentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
