# Generated by Django 4.2.4 on 2023-09-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_push_postcommentid_push_stepcommentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='summary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
